# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# Swedish keyboard layout with caps as ctrl
input {
    kb_layout = se
    kb_options = caps:ctrl_modifier
}
