# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Kitty terminal blur
windowrule = match:class ^(kitty)$, opacity 0.85 override
#windowrule = match:class ^(kitty)$, blur on
